- README.md
- package.json
- src/index.ts
- webpack.config.js
.mjs file is not working in worker.js
package.json browser has more preference than main while using it in react application.
> kf migration updates

- README.md
- src/index.ts
Updated Documentations and changed initialise method to initialize
> 📝 Docs update

- src/index.ts
- src/lowcode.ts
- src/types/internal.ts
✨ global fetch support added in kf.api
Added initialise method
> ✨ global fetch support added in kf.api

- .gitignore
- custom.build.mjs
- lowcode.types.json
- nocode.types.json
- package.json
- src/nocode.ts
- vite.config.js
> ### ⭐  Kind Based Typings Split 🌟 
Based on kind generated a multiple typings file. (Lowcode & NoCode)
Currently we generate a typings file from lowcode.ts (which contains all the classes related apps + forms), But we are extending support for events in No Code Env (Outside of Apps) so here in the editor we have to show suggestions only for the forms.
> ⭐  Kind Based Typings Split 🌟 

- README.md
- src/types/external.ts
Removed UserType from userObject
> 🔥  Removed UserType

- README.md
- src/snippets/snippets.json
Added a snippet for setSelectedItem.
Docs update for showConfirm
> 📝 added set selected item in snippet and doc change

- .github/workflows/publish.create.component.yml
- packages/create-component/package.json
> 🐛 Create component package.json fix

- packages/create-component/template/react/vite.config.js
- packages/create-component/template/vannila/vite.config.js
- packages/sdk/src/app/index.ts
- packages/sdk/src/app/page.ts
- packages/sdk/src/core/index.ts
- packages/sdk/src/index.ts
- packages/sdk/src/snippets/snippets.json
> Fix : Json variable sync read write disabled

- .github/workflows/publish.sdk.yml
> Fix : version upgraded in sdk git action file

- packages/sdk/custom.build.mjs
- packages/sdk/src/app/dataform.ts
- packages/sdk/src/app/index.ts
- packages/sdk/src/app/page.ts
- packages/sdk/src/board/index.ts
- packages/sdk/src/index.ts
- packages/sdk/src/utils/client.ts
-   [x] Verified `.d.ts` file for new class/method.
-   [x] SDK Issue fix PR
-   [x] Doesn't affect the previous method signatures.
> 🐛 typings fixes

- .github/PULL_REQUEST_TEMPLATE.md
- packages/sdk/package.json
-   [x] SDK Issue fix PR
-   [x] Doesn't affect the previous method signatures.
> 🔖 fix: package version bump

- packages/sdk/package.json
- packages/sdk/src/form/index.ts
- packages/sdk/src/lowcode.ts
- packages/sdk/src/nocode.ts
- packages/sdk/src/types/external.ts
-   [x] Verified `.d.ts` file for new class/method.
-   [x] SDK Issue fix PR
-   [x] Updated version in `package.json`
-   [x] Doesn't affect the previous method signatures.
> fetch, addrows types fixe

- .github/workflows/greeting.yml
greetings workflow added.
will trigger only for firsttime contributor
> Greeting workflow added

- packages/create-component/package.json
- packages/create-component/scaffolders/page/template/react/vite.config.js
- packages/create-component/scaffolders/page/template/vannila/vite.config.js
- packages/form-field-scripts/package.json
- packages/form-field-scripts/src/config/webpack.config.js
- packages/form-field-scripts/src/scripts/build.js
- packages/form-field-scripts/src/scripts/dev.js
- pnpm-lock.yaml
> added all the folders that I need to the files in packages.json

- packages/sdk/package.json
- packages/sdk/src/types/external.ts
-   [X] Updated version in `package.json`
-   [X] Verified `.d.ts` file for new class/method.
> feat: :sparkles: adding AppRoles and deprecationg Role from kf.user

- README.md
- docs/src/content/docs/utils.md
- packages/sdk/package.json
- packages/sdk/src/types/external.ts
-   [x] Updated version in `package.json`
-   [x] Verified `.d.ts` file for new class/method.
> Role switch - Added kf.user.AppRoles and deprecated kf.user.Role

- packages/sdk/src/app/component.ts
> Deprication warning: Depricated Show and hide method due to condition visibility

- docs/src/constants.js
- docs/src/content/docs/app/Page/openPopup.md
- docs/src/content/docs/app/openPage.md
- docs/src/content/docs/component.md
- docs/src/content/docs/context.md
- docs/src/content/docs/form/Table/addRow.md
- docs/src/content/docs/form/Table/addRows.md
- docs/src/content/docs/form/Table/deleteRow.md
- docs/src/content/docs/form/Table/deleteRows.md
- docs/src/content/docs/form/Table/getRow.md
- docs/src/content/docs/form/Table/getRows.md
- docs/src/content/docs/form/Table/toJson.md
- docs/src/content/docs/index.mdx
> Changed base url

- docs/src/content/docs/app/board.md
- docs/src/content/docs/app/dataform.md
- docs/src/content/docs/app/decision.table.md
- docs/src/content/docs/app/index.md
- docs/src/content/docs/form/Table/Row/getField.md
- docs/src/content/docs/form/Table/Row/getParent.md
- docs/src/content/docs/form/Table/addRow.md
- docs/src/content/docs/form/Table/getRow.md
- docs/src/content/docs/form/Table/toJson.md
- docs/src/content/docs/form/updateField.md
- docs/src/content/docs/integration.md
> Forms, boards, dataforms, decision table changes

- docs/src/content/docs/form/Table/addRow.md
> Typo correction

- docs/src/content/docs/app/board.md
- docs/src/content/docs/app/dataform.md
- docs/src/content/docs/app/decision.table.md
- docs/src/content/docs/form/Table/Row/getField.md
- docs/src/content/docs/form/Table/Row/getParent.md
- docs/src/content/docs/form/Table/Row/updateField.md
- docs/src/content/docs/form/Table/addRow.md
- docs/src/content/docs/form/Table/addRows.md
- docs/src/content/docs/form/Table/deleteRow.md
- docs/src/content/docs/form/Table/deleteRows.md
- docs/src/content/docs/form/Table/getRow.md
- docs/src/content/docs/form/Table/getRows.md
- docs/src/content/docs/form/Table/toJson.md
- docs/src/content/docs/form/about.md
- docs/src/content/docs/form/getField.md
- docs/src/content/docs/form/getTable.md
- docs/src/content/docs/form/updateField.md
- docs/src/content/docs/integration.md
> Style guide based changes

- packages/sdk/src/board/index.ts
- packages/sdk/src/types/external.ts
> VIew ID Added in sdk

- .github/workflows/publish.docs.yml
> fix: bumped deploy-pages to v4

- packages/form-field-config/package.json
- packages/form-field-scripts/package.json
> bumped patch version for form-field-config & form-field-scripts

- packages/form-field-scripts/package.json
> bumped form-field-scripts version

- docs/src/content/docs/index.mdx
> changed link to getting started

- docs/src/content/docs/components/formField.md
- packages/create-component/package.json
> bumped version for create-kf-component

- docs/src/content/docs/components/formField.md
- docs/src/content/docs/components/page.md
- docs/src/content/docs/form/Table/Row/getField.md
- docs/src/content/docs/form/Table/Row/getParent.md
- docs/src/content/docs/form/Table/Row/toJson.md
- docs/src/content/docs/form/Table/Row/updateField.md
-   [x] Documentation updates
Replaced kf.context with rowInstance and changed the installation command for form component.
> Sdk edit june

- packages/create-component/package.json
- packages/create-component/scaffolders/form-field/project-template/_package.json
> create-component - form field package node version update
